#declare Events=array[16] {
//Event Time from drop (sec)
/* 0:Drop*/	                      0.00
/* 1:S1 Ignition*/,	              5.00
/* 2:S1 Burnout*/,	             76.52
/* 3:S1 Drop*/,	                 91.04
/* 4:S2 Ignition*/,	             91.44
/* 5:Fairing Drop Start*/,	    127.68
/* 6:S2 Burnout*/,	            164.60
/* 7:S2 Drop*/,	                413.20
/* 8:S3 Ignition*/,	            424.24
/* 9:S3 Burnout*/,	            491.84
/*10:S3 Separation*/,	          611.84
/*11:CCAM Attitude Maneuver*/,	614.84
/*12:Turn off TLM transmitter*/,671.84
/*13:Crabwalk Start*/,	        911.84
/*14:Crabwalk Finish*/,	       1211.84
/*15:Sequence End*/,	         1246.84
}
