#declare Events=array[16] {
//"Event","Time from drop (sec)"
/* 0: Drop"*/                       0.00
/* 1: Stage 1 Ignition"*/,          5.00
/* 2: Stage 1 Burnout"*/,          76.36
/* 3: Stage 1 Separation"*/,       90.76
/* 4: Stage 2 Ignition"*/,         91.60
/* 5: Fairing Separation"*/,      127.60
/* 6: Stage 2 Burnout"*/,         165.60
/* 7: Stage 2 Separation"*/,      413.04
/* 8: Stage 3 Ignition"*/,        424.08
/* 9: Stage 3 Burnout"*/,         492.96
/*10: Payload Separation"*/,      552.96
/*11: CCAM Attitude Maneuver"*/,  555.96
/*12: Turn off TLM transmitter"*/,612.96
/*13: Crabwalk Start"*/,          852.96
/*14: Crabwalk Finish"*/,        1152.96
/*15: Sequence End"*/,           1187.96
}
